### ISSUE TITLE
https化

### ISSUE THREAD

**Issue by smile-0yen** [rehashfm/rehash.fm#43]

**Comment by YuzuruS** [comment]
これだけでできそう
https://blog.github.com/2018-05-01-github-pages-custom-domains-https/

**Comment by azihsoyn** [comment]
おぉ！

**Comment by smile-0yen** [comment]
## Before 
dig rehash.fm

; <<>> DiG 9.10.6 <<>> rehash.fm
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 7636
;; flags: qr rd ra; QUERY: 1, ANSWER: 2, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
;; QUESTION SECTION:
;rehash.fm.			IN	A

;; ANSWER SECTION:
rehash.fm.		3600	IN	A	192.30.252.154
rehash.fm.		3600	IN	A	192.30.252.153

;; Query time: 564 msec
;; SERVER: 2001:730:3ec2::11#53(2001:730:3ec2::11)
;; WHEN: Tue Jun 26 01:00:12 IST 2018
;; MSG SIZE  rcvd: 70

## After
dig rehash.fm

; <<>> DiG 9.10.6 <<>> rehash.fm
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 53891
;; flags: qr rd ra; QUERY: 1, ANSWER: 4, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
;; QUESTION SECTION:
;rehash.fm.			IN	A

;; ANSWER SECTION:
rehash.fm.		3600	IN	A	185.199.109.153
rehash.fm.		3600	IN	A	185.199.110.153
rehash.fm.		3600	IN	A	185.199.108.153
rehash.fm.		3600	IN	A	185.199.111.153

;; Query time: 943 msec
;; SERVER: 2001:730:3ec2::11#53(2001:730:3ec2::11)
;; WHEN: Tue Jun 26 01:16:42 IST 2018
;; MSG SIZE  rcvd: 102

**Comment by smile-0yen** [comment]
- CNAMEを削除→戻す、で反映された模様。
- スマイル手元からはエラーあり。
- ふそやん手元からは正常に見えておりおそらく環境の問題。

**Comment by YuzuruS** [comment]
内部で使ってるコンテンツがhttpなのでエラーでてるっぽい。
<img width="819" alt="2018-06-26 10 16 46" src="https://user-images.githubusercontent.com/1485195/41883548-1143fa0a-792a-11e8-894f-1d6baa4e1dec.png">

**Comment by azihsoyn** [comment]
:naruhodo:

**Comment by smile-0yen** [comment]
https://github.com/rehashfm/rehash.fm/commit/f7b416e0cc0bae2b4e44e486c26c52ab8d0a78a3
完了してるのでクローズ
